print(typeof(1))
print(typeof(-10.4))
print(typeof(NaN))
print(as.integer(1))
print(typeof(as.integer(1)))
print(as.numeric(as.integer(5)))
print(typeof(as.numeric(as.integer(5))))
print(as.integer(10) + 5)
print(typeof(2+3i))
print(typeof(TRUE))
print(typeof(FALSE))
print(typeof(T))
print(20 > 20)
print(40 == 39+1)
print(!FALSE)
print(TRUE || FALSE)
print(as.logical(1))
print(as.logical(0))
print(as.logical(-3))
print(as.numeric(FALSE))
print(as.numeric(TRUE))
print("cat")
print(typeof("cat"))
print(typeof("13"))
print(as.character("13"))